### PR TITLE
docs: add example use nested router usage

### PR DESCRIPTION
**Pull request by nopeless**
It was hard to figure out

### CODE REVIEW

**Comment by nopeless** [comment]
@pi0 By the way, I realized later on that it gives a deprecation warning. I simply could not find a fix though. Would you mind amending my PR?

**Comment by nopeless** [comment]
#253 is the tracker

**Comment by Atinux** [comment]
Could you please check with latest release of `h3` if: `app.use('/api', router)` works?

**Comment by nopeless** [comment]
> Could you please check with latest release of `h3` if: `app.use('/api', router)` works?

sure

**Comment by nopeless** [comment]
@Atinux It appears to not work. In fact, I cannot get nested router to work at all on the main branch

**Comment by nopeless** [comment]
@pi0 This needs investigation

**Comment by Atinux** [comment]
Do you mind sharing a Stackblitz or GitHub repo @nopeless ?

**Comment by nopeless** [comment]
> Do you mind sharing a Stackblitz or GitHub repo @nopeless ?

Well, would you mind doing that? There are currently no tests that prove that this works so it would be better to prove that it works

**Comment by nopeless** [comment]
> Could we use middleware to nested route, if it works again?

There is no big distinction between middleware and nested router in h3. I am assuming that a middleware pattern can temporary stub a different baseurl in order for the radix3 router to work properly but that is just a very bad idea in general. There are so many undocumented things going on that I am not sure what the actual root cause is. Best thing to do is to wait until maintainers resolve this

**Comment by pi0** [comment]
Here is an example using nested routers: https://stackblitz.com/edit/github-2bmusk?file=app.ts&startScript=dev

**Pull request closed without merging**
