### PR TITLE
feat: handle asyncs returning without closing res

### PR DESCRIPTION
**Pull request by xhebox**
refer the analysis in #35

What I am doing in my handler:

```ts
const app = fastify()

export default async function (req: unknown, res: unknown) {
    await app.ready()
    app.server.emit('request', req, res)
}
```

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks for the PR.

Would you mind adding a test for it?

**Comment by pi0** [comment]
You can do the async initialization using `lazyHandle`:

```js
import { lazyHandle } from 'h3'

export default lazyHandle(async () => {
  const app = fastify()
  await app.ready()
  return (req, res) => {
    // ... 
  }
})
```

**Comment by xhebox** [comment]
> ```js
> lazyHandle
> ```

I could check it that works, later. But I think h3 should handle the case by default, if possible.

**Comment by xhebox** [comment]
closed since it is outdated

**Pull request closed without merging**
