### PR TITLE
fix(withBase): update with `pathname` instead of `path`

### LINKED ISSUE #878: event.url.pathname is updated incorrectly in withBase method for NodeEvents
### Environment

Node.js v20.17.0
h3-nightly@2.0.0-1725475522.2d941d3

### Reproduction

Given this simple H3-nightly app running on node.js-
```ts
import { createH3, toNodeHandler, withBase } from "h3-nightly";
import { createServer } from "http";

const router = createH3()
    .get('/', (_event) => 'hello')
    .get('/abc', (_event) => 'abc')
    .use((event) => { console.log(event.path, event.pathname) })

const app = createH3()
    .use('/app/**', withBase('/app', router))

const port = 3000
createServer(toNodeHandler(app))
    .listen(port, () => console.log('started', `http://localhost:${port}`));
```

The url `'http://localhost:3000/app/abc/'` is resolved correctly.
But the same url with any searchParams like `'http://localhost:3000/app/abc/?'` is not resolved, sending 404.

### Describe the bug

The event path and pathname are updated incorrectly by the `set pathname`, when called from the `withBase` function.

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by gulshan**
resolves #878

### CODE REVIEW

**Comment by pi0** [comment]
Can you please add a test as well? 🙏🏼

**Comment by gulshan** [comment]
@pi0 The issue was only happening with `toNodeHandler` and most probably tied to how the `pathname` property is set in `NodeReqURLProxy`. But I put the fix in the common code. So, I am a bit confuse about how I should test it.

**Comment by gulshan** [comment]
@pi0 Tried adding an integration test. Please check.

**Review by pi0 — APPROVED** [review]
Thanks ❤️

**Pull request merged**
