### PR TITLE
docs: add `h3-typebox` utils to readme

### PR DESCRIPTION
**Pull request by kevinmarrec**
Add documentation about https://github.com/kevinmarrec/h3-typebox for JSON Schema Validation.

### CODE REVIEW

**Comment by pi0** [comment]
Thanks! Before listing, it would be nice if you can update h3-typebox with two items:

- Update to accept `CompatibilityEvent` as argument (it needs a major release maybe)
- Update validator names to `validateBody` / `validateQuery`. H3 already deprecate usage of `use` prefix (#156)

**Comment by kevinmarrec** [comment]
@pi0 Got it, will work on these updates !

**Comment by kevinmarrec** [comment]
@pi0 Isn't my package already using `CompatibilityEvent` ?

**Comment by kevinmarrec** [comment]
Also, gonna wait for next `h3` release for https://github.com/unjs/h3/pull/156

**Comment by pi0** [comment]
Alright. I think only readme needs to update `req` to `event.

I will release h3 today btw you can also rename utils without waiting for it. It is just a new convention.

**Comment by pi0** [comment]
Thanks!

**Pull request merged**
