### PR TITLE
feat(useSession): support custom session id generator

### PR DESCRIPTION
**Pull request by maou-shonen**
Sometimes it may be necessary to customize the session ID.
for example, using something like `crypto.randomBytes(20).toString('base64url')`.
having a method available in the session configuration would be convenient.

### CODE REVIEW

**Comment by maou-shonen** [comment]
Do I need to create a session.test.ts?
Should I open another PR?

**Comment by Atinux** [comment]
What would be the use case to customize the ID generation?

**Review by pi0 — APPROVED** [review]
Thanks!

**Comment by pi0** [comment]
>  What would be the use case to customize the ID generation?

I have no usecase but makes sense to make id generation customizable (shorter, compatible with backend, more secure, crypto incompatibility, etc could be some reasons)

**Comment by maou-shonen** [comment]
> What would be the use case to customize the ID generation?

Obviously, I'm replying late,😅
One of my real-world use cases is that I can set the session ID to be the same as the ID from external login (usually OAuth2),
This way, I don't need to use two DB fields or `session.data.id` to associate them.

**Pull request merged**
