### PR TITLE
fix(proxy): avoid decoding request body as utf8

### PR DESCRIPTION
**Pull request by Ngob**
### 🔗 Linked issue
[#413](https://github.com/unjs/h3/issues/413)

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Resolves [#413](https://github.com/unjs/h3/issues/413)

This pull-request add:
 - A test to test if the proxy preserve the PDF file when sending the file to the upstream service. I added a PDF file into the test/ressource directory
 - A fix that stream the request body to the upstream service. It allow better memory usage and prevent any conversion on the body

This PR consists into 2 commit: 
 - The first commit does add the test. In this commit you can see the test failing
 - The second commit does add the fix. In this commit, you can see the test not failing anymore

Let me know if I need to update the PR.
Any comments would be appreciated.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly (does not apply here).

### CODE REVIEW

**Comment by Ngob** [comment]
Hello,

I added another test to improve the coverage that test if additionnals headers are being proxifyed along with the request header
I also tested on node version 16, 18 and 19 and added the "duplex: 'half'" to make it work using version 18/19. The pipeline should be fixed now.

Thanks for the review

**Comment by pi0** [comment]
Hi and thanks for the PR. I think it is a good idea to support incoming request body streaming but it only works on Node.js and we have an ongoing draft for it (https://github.com/unjs/h3/pull/374). Is there any chance we might be able to fix `readRawBody` directly? (it is supposed to properly read "binary" request body into a Buffer if there is any possible bug with it..)

**Comment by Ngob** [comment]
> Hi and thanks for the PR. I think it is a good idea to support incoming request body streaming but it only works on Node.js and we have an ongoing draft for it (#374). Is there any chance we might be able to fix `readRawBody` directly? (it is supposed to properly read "binary" request body into a Buffer if there is any possible bug with it..)

Yes I can do
So what I need to do is to restore the usage of readRawBody and fix the method when using binaries?
So I will update tests to check that readRawBody has the correct behavior

**Comment by pi0** [comment]
Thanks for helping on this by providing reproduction, explanations and fixtures ❤️ 

I have made a refactor to simplify fix (We need to pass `false` as second argument to `readRawBody` to make it reading body as a stream).

Using proxy for incoming requests seems a good idea too! Leveraging `event.request` introduced in #454 we can implement this feature in #374 (an experimental flag at first)

**Comment by Ngob** [comment]
Thanks a lot for the followup!

**Pull request merged**
